### ISSUE TITLE
TinyMCE Bundle all 2.10.1 doesn't work anymore with Contao 4.12.

### ISSUE THREAD

**Issue by Arachnophilia** [cliffparnitzky/TinyMceBundleAll#3]
Hello Cliff
I have installed the "TinyMCE Bundle all" under the new Contao 4.12.1, but the bundle is not available for use.
Nothing is displayed.
No errors are reported during the installation and database update.

Greeting Joerg

**Comment by cliffparnitzky** [comment]
Refers to https://github.com/cliffparnitzky/TinyMcePluginLoader/issues/16
